const TrainData = [
  {
    trainNumber: "12192",
    trainName: "JBP NZM SF EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "12:00",
    departureTime: "04:20",
    distance: "403",
    duration: "07:40",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "18477",
    trainName: "UTKAL EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "13:05",
    departureTime: "04:55",
    distance: "403",
    duration: "08:10",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["SP"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "C",
  },
  {
    trainNumber: "16031",
    trainName: "ANDAMAN EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "20:55",
    departureTime: "13:38",
    distance: "410",
    duration: "07:17",
    runningMon: "Y",
    runningTue: "N",
    runningWed: "N",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "N",
    avlClasses: ["2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12171",
    trainName: "LTT HW AC EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "06:40",
    departureTime: "00:45",
    distance: "403",
    duration: "05:55",
    runningMon: "N",
    runningTue: "Y",
    runningWed: "N",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "N",
    avlClasses: ["1A", "2A", "3A"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "18237",
    trainName: "CHATTISGARH EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "19:50",
    departureTime: "12:00",
    distance: "403",
    duration: "07:50",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "C",
  },
  {
    trainNumber: "12715",
    trainName: "SACHKHAND EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "13:05",
    departureTime: "06:28",
    distance: "410",
    duration: "06:37",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12617",
    trainName: "MANGLADWEEP EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "13:35",
    departureTime: "06:38",
    distance: "403",
    duration: "06:57",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12779",
    trainName: "GOA EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "06:25",
    departureTime: "23:20",
    distance: "403",
    duration: "07:05",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12615",
    trainName: "GRAND TRUNK EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "05:05",
    departureTime: "22:55",
    distance: "410",
    duration: "06:10",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "22691",
    trainName: "RAJDHANI EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "05:30",
    departureTime: "00:21",
    distance: "403",
    duration: "05:09",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A"],
    trainType: ["R"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12155",
    trainName: "RKMP NZM SF EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "07:50",
    departureTime: "02:32",
    distance: "403",
    duration: "05:18",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "12279",
    trainName: "TAJ EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "21:35",
    departureTime: "15:20",
    distance: "410",
    duration: "06:15",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["CC", "2S"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "D",
  },
  {
    trainNumber: "20171",
    trainName: "VANDE BHARAT EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "13:16",
    departureTime: "08:43",
    distance: "403",
    duration: "04:33",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "Y",
    avlClasses: ["EC", "CC"],
    trainType: ["S"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "11841",
    trainName: "KURJ KKDE EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "08:45",
    departureTime: "23:53",
    distance: "410",
    duration: "08:52",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "D",
  },
  {
    trainNumber: "12137",
    trainName: "PUNJAB MAIL",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "21:25",
    departureTime: "14:23",
    distance: "410",
    duration: "07:02",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "12285",
    trainName: "NZM DURONTO EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "10:40",
    departureTime: "05:35",
    distance: "403",
    duration: "05:05",
    runningMon: "Y",
    runningTue: "N",
    runningWed: "N",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "N",
    avlClasses: ["1A", "2A", "3A", "SL", "2S"],
    trainType: ["D"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "20805",
    trainName: "AP EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "05:40",
    departureTime: "00:11",
    distance: "410",
    duration: "05:29",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL", "2S"],
    trainType: ["SP"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "C",
  },
  {
    trainNumber: "22221",
    trainName: "NZM RAJDHANI",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "09:55",
    departureTime: "05:11",
    distance: "403",
    duration: "04:44",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A"],
    trainType: ["R"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "12919",
    trainName: "MALWA EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "04:15",
    departureTime: "21:38",
    distance: "410",
    duration: "06:37",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "22685",
    trainName: "CDG SKRANTI EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "11:55",
    departureTime: "04:33",
    distance: "410",
    duration: "07:22",
    runningMon: "Y",
    runningTue: "N",
    runningWed: "N",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "N",
    avlClasses: ["1A", "2A", "3A", "CC", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "22469",
    trainName: "VANDE BHARAT EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "23:10",
    departureTime: "18:25",
    distance: "403",
    duration: "04:45",
    runningMon: "N",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["EC", "CC"],
    trainType: ["S"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "D",
  },
  {
    trainNumber: "12627",
    trainName: "KARNATAKA EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "09:00",
    departureTime: "02:58",
    distance: "410",
    duration: "06:02",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12649",
    trainName: "SAMPARK KRANTI",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "08:10",
    departureTime: "02:48",
    distance: "403",
    duration: "05:22",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12625",
    trainName: "KERALA SF EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "13:30",
    departureTime: "07:30",
    distance: "410",
    duration: "06:00",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "22181",
    trainName: "JBP NZM SF EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "04:10",
    departureTime: "22:43",
    distance: "403",
    duration: "05:27",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "12823",
    trainName: "CG SMPRK KRANTI",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "07:40",
    departureTime: "02:18",
    distance: "403",
    duration: "05:22",
    runningMon: "N",
    runningTue: "Y",
    runningWed: "N",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "C",
  },
  {
    trainNumber: "12807",
    trainName: "SAMTA EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "18:10",
    departureTime: "11:40",
    distance: "403",
    duration: "06:30",
    runningMon: "Y",
    runningTue: "N",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "C",
  },
  {
    trainNumber: "12409",
    trainName: "GONDWANA SF EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "05:00",
    departureTime: "23:38",
    distance: "403",
    duration: "05:22",
    runningMon: "Y",
    runningTue: "N",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "N",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "C",
  },
  {
    trainNumber: "12189",
    trainName: "MAHAKAUSHAL EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "11:00",
    departureTime: "03:48",
    distance: "403",
    duration: "07:12",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "12641",
    trainName: "TIRUKKURAL EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "18:35",
    departureTime: "12:13",
    distance: "403",
    duration: "06:22",
    runningMon: "N",
    runningTue: "N",
    runningWed: "N",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "Y",
    avlClasses: ["2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12001",
    trainName: "NDLS SHATABDI",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "23:50",
    departureTime: "18:45",
    distance: "410",
    duration: "05:05",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["EC", "CC"],
    trainType: ["S"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "11077",
    trainName: "JHELUM EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "21:20",
    departureTime: "13:58",
    distance: "410",
    duration: "07:22",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "12441",
    trainName: "BSP NDLS RAJ EX",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "10:40",
    departureTime: "05:25",
    distance: "410",
    duration: "05:15",
    runningMon: "N",
    runningTue: "Y",
    runningWed: "N",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "N",
    avlClasses: ["1A", "2A", "3A"],
    trainType: ["SP"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "C",
  },
  {
    trainNumber: "12485",
    trainName: "NED SGNR SF EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "10:10",
    departureTime: "04:09",
    distance: "410",
    duration: "06:01",
    runningMon: "N",
    runningTue: "Y",
    runningWed: "N",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "N",
    avlClasses: ["2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "11057",
    trainName: "CSMT ASR EXPRESS",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "03:40",
    departureTime: "20:28",
    distance: "410",
    duration: "07:12",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["2A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "B",
  },
  {
    trainNumber: "12447",
    trainName: "UP SMPRK KRANTI",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "05:22",
    departureTime: "23:30",
    distance: "403",
    duration: "05:52",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "D",
  },
  {
    trainNumber: "12723",
    trainName: "TELANGANA EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "07:40",
    departureTime: "01:24",
    distance: "410",
    duration: "06:16",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12621",
    trainName: "TAMILNADU SF EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NDLS",
    arrivalTime: "06:30",
    departureTime: "00:31",
    distance: "410",
    duration: "05:59",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["1A", "2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "12687",
    trainName: "MDU CDG SF EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "21:35",
    departureTime: "14:33",
    distance: "403",
    duration: "07:02",
    runningMon: "N",
    runningTue: "Y",
    runningWed: "N",
    runningThu: "N",
    runningFri: "Y",
    runningSat: "N",
    runningSun: "N",
    avlClasses: ["2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
  {
    trainNumber: "14623",
    trainName: "PATALKOT EXP",
    fromStnCode: "VGLJ",
    toStnCode: "DSJ",
    arrivalTime: "03:26",
    departureTime: "20:48",
    distance: "407",
    duration: "06:38",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["2A", "3A", "3E", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "C",
  },
  {
    trainNumber: "12721",
    trainName: "DAKSHIN EXP",
    fromStnCode: "VGLJ",
    toStnCode: "NZM",
    arrivalTime: "03:40",
    departureTime: "21:28",
    distance: "403",
    duration: "06:12",
    runningMon: "Y",
    runningTue: "Y",
    runningWed: "Y",
    runningThu: "Y",
    runningFri: "Y",
    runningSat: "Y",
    runningSun: "Y",
    avlClasses: ["2A", "3A", "SL"],
    trainType: ["O"],
    atasOpted: "false",
    flexiFlag: "false",
    trainOwner: "0",
    trainsiteId: "M",
  },
];

export default TrainData;
